services:
  web:
    build:
      context: .
      dockerfile: ./DockerBuilds/DockerDevelopment/Dockerfile
    volumes:
      - .:/FEC
    ports:
      - "3000:3000"
  redis:
    ports:
      - "6379:6379"