#rebuild with docker-compose build
#launch with docer-compose up
version: "3.9"
services:
  web:
    image: fec_web
    depends_on:
      - redis
    links:
      - "6379:redis"
  redis:
    image: "redis:alpine"